export interface ResourceNode {
  id: string;
  name: string;
  type: 'folder' | 'file';
  children?: ResourceNode[];
  description?: string;
  quickStart?: string;
  status?: 'active' | 'documents' | 'coming_soon';
  toolRoute?: string;
  toolLabel?: string;
  icon?: string;
  color?: string;
  documentId?: string;
  fileName?: string;
  fileType?: string;
  fileSize?: number;
  modelerSummary?: string;
  keyTakeaways?: string[];
  relatedIds?: string[];
}

function file(
  id: string,
  documentId: string,
  fileName: string,
  fileType: string,
  fileSize: number,
  modelerSummary?: string,
  keyTakeaways?: string[],
): ResourceNode {
  return { id, name: fileName, type: 'file', documentId, fileName, fileType, fileSize, modelerSummary, keyTakeaways };
}

export const RESOURCE_TREE: ResourceNode = {
  id: 'root',
  name: '07 - Engineering-Doc Control',
  type: 'folder',
  icon: 'FolderRoot',
  color: 'blue',
  description: 'All BIM documentation, specifications, and standards for Project Confluence.',
  children: [
    {
      id: 'specs',
      name: '7.05 Specifications',
      type: 'folder',
      icon: 'FileText',
      color: 'indigo',
      description: 'Engineering specifications governing pipe supports, materials, and installation.',
      quickStart: 'Pipe support placement starts here. Use the Calculator tool for span lookup, guide spacing, and hardware selection. Metal spans are 2-3x longer than plastic spans.',
      status: 'active',
      toolRoute: '/calculator',
      toolLabel: 'Pipe Support Calculator',
      children: [
        {
          id: 'specs-process',
          name: '40 - Process Interconnections',
          type: 'folder',
          icon: 'Workflow',
          color: 'indigo',
          description: 'Pipe support and anchor specifications for process piping systems.',
          children: [
            file('pipe-supports-r3', 'pipe-supports-r3',
              '40_05_19 - Pipe Supports and Anchors R3.pdf', 'pdf', 9917847,
              'The master specification for pipe support design. Defines support types (slide, guide, anchor, hanger), placement rules, hardware selection, and material requirements for all piping systems.',
              [
                'Four support types: Slide (vertical only), Guide (vertical + lateral), Anchor (full restraint), Hanger (suspension)',
                'Guide spacing = 2x deadweight span',
                'Plastic fittings: support within 18" of centerline',
                'Corrosive areas: 316/316L stainless steel only',
                'No friction anchors (Cush-a-Clamp) on plastic pipe',
                'Stainless/copper must be dielectrically insulated from carbon steel supports',
              ],
            ),
            file('span-tables-r0', 'span-tables-r0',
              '40_05_19.01 - Span Tables R0.pdf', 'pdf', 828300,
              'Maximum support spacing tables by material, size, temperature, and service. This is the primary lookup reference for placing supports in the model.',
              [
                'Match material + schedule + service + temperature to find max span',
                'Apply SG correction factor if fluid density > 1.0',
                'If span < 2.5 ft, use continuous support',
                'Carbon steel: longest spans (~19 ft for 4")',
                'Plastics: shortest spans (4-7 ft range depending on material/temp)',
              ],
            ),
          ],
        },
        {
          id: 'specs-legends',
          name: 'P&ID Legend Sheets',
          type: 'folder',
          icon: 'FileSpreadsheet',
          color: 'indigo',
          description: 'P&ID symbol definitions for mechanical, process, and instrumentation drawings.',
          children: [
            file('ocs-legend-1', 'ocs-legend-1', 'OCS Legend Sheet 1 - General Symbols Rev.0.pdf', 'pdf', 474288,
              'General mechanical, process, and instrumentation legend. Defines base symbols used across all P&ID sheets.',
            ),
            file('ocs-legend-2', 'ocs-legend-2', 'OCS Legend Sheet 2 - Rev.2 markup.pdf', 'pdf', 856668,
              'Continued symbol definitions with markup revisions. Check this for the latest symbol updates.',
            ),
            file('ocs-legend-3', 'ocs-legend-3', 'OCS Legend Sheet 3 - Rev.1.pdf', 'pdf', 521928,
              'Additional legend symbols for specialized equipment and instrumentation.',
            ),
            file('ocs-legend-4', 'ocs-legend-4', 'OCS Legend Sheet 4 - Rev.3 markup.pdf', 'pdf', 564952,
              'Latest legend sheet with Rev.3 markups. Check this for the most current symbol definitions.',
            ),
          ],
        },
      ],
    },
    {
      id: 'bim',
      name: '7.20 BIM',
      type: 'folder',
      icon: 'Building2',
      color: 'blue',
      description: 'BIM standards, welcome package, and project models.',
      children: [
        {
          id: 'welcome',
          name: '7.20.00 Welcome Package',
          type: 'folder',
          icon: 'BookOpen',
          color: 'blue',
          description: 'Onboarding documents for all BIM team members. Start here on your first day.',
          children: [
            {
              id: 'f00',
              name: '00_BIM CPEP and BIM Requirements',
              type: 'folder',
              icon: 'FileCheck',
              color: 'blue',
              status: 'active',
              toolRoute: '/upload',
              toolLabel: 'P&ID Extraction',
              description: 'Core BIM requirements, project execution plan, and coordination procedures.',
              quickStart: 'Before you start modeling, read the CPEP to understand the project delivery workflow (DM > CM > FM > IFF). Your model goes through 7 audit phases. Know your LOD requirements.',
              children: [
                file('cpep-wip', 'cpep-wip',
                  'CPEP BIM 3D Design WIP.pdf', 'pdf', 177953,
                  'The Construction Project Execution Plan for BIM. Defines the delivery workflow from Design Model through IFF to As-Built.',
                  [
                    'Delivery workflow: DM > CM > FM > IFF > As-Built',
                    'Model goes through 7 audit phases (DC + DMS compliance)',
                    'Know your discipline LOD requirements before modeling',
                  ],
                ),
                file('contractor-bim-req', 'contractor-bim-req',
                  'Contractor BIM Requirements 2024.pdf', 'pdf', 127951,
                  'Client-issued BIM requirements for all contractors. Defines what the client expects in terms of LOD, deliverables, and coordination.',
                  [
                    'LOD, deliverable format, and coordination rules set by the client',
                    'Must comply with these requirements -- they override internal standards where they conflict',
                  ],
                ),
                file('bim-coordination-guide', 'bim-coordination-guide',
                  'Project Confluence BIM Modeling and Coordination Guide.pdf', 'pdf', 331831,
                  'Complete guide for BIM modeling and coordination on Project Confluence. Covers model accuracy, coordination workflow, and quality requirements.',
                  [
                    'Model accuracy requirements and coordination workflow',
                    'Clash detection and resolution procedures',
                    'Quality gates and review checkpoints',
                  ],
                ),
                {
                  id: 'f00-eagle',
                  name: 'Eagle',
                  type: 'folder',
                  icon: 'FolderOpen',
                  color: 'blue',
                  description: 'Eagle project-specific BIM requirements, CPEP, and OSM shared parameters.',
                  children: [
                    file('eagle-bim-req', 'eagle-bim-req',
                      'Hoffman BIM Requirements Rev4.4.pdf', 'pdf', 512000,
                      'Contract-level BIM requirements between Hoffman and Eagle subcontractors. Defines LOD, discipline-specific modeling, IFF rules, file naming, formats, and required attributes.',
                      [
                        'File naming: XCCBBB-LLL-UUU-DD-SSSSS-AAA-MM format',
                        'Deliver DWG + NWC (or RVT + NWC if Revit primary)',
                        'LOD 400 for CM unless approved otherwise',
                        'Accuracy: ±1" standard, ±1/4" in dedicated routing zones',
                        'Required attributes: HCC_IFF_ID, HCC_PKG_ID, INT_RFI, INT_PKG_Name',
                        'Files due 3 PM day before coordination meeting',
                      ],
                    ),
                    file('eagle-cpep', 'eagle-cpep',
                      'Hoffman EAGLE CPEP for BIM 3D Design.pdf', 'pdf', 680000,
                      'Full BIM Construction Project Execution Plan for Intel Project Eagle. Covers roles, BIM 360, BIM Track, DM/CM/FM structure, coordination, IFF, model-to-field, and closeout.',
                      [
                        'Coordinates: Ocotillo Campus system',
                        'Software: Revit 2021.1.x, AutoCAD 2018 save format, Navisworks 2021',
                        'CM upload: at least 2x weekly and day before meetings',
                        'IFF via Procore: conceptual then technical review',
                        'Conditional items resolved in 14 days',
                        'Monumental scope gets routing priority (OSM modules, large duct, steel)',
                      ],
                    ),
                    file('eagle-osm-shared-params', 'eagle-osm-shared-params',
                      'Hoffman OSM Shared Parameters.pdf', 'pdf', 145000,
                      'OSM-specific shared parameter requirements for Eagle project.',
                    ),
                  ],
                },
                {
                  id: 'f00-paragon',
                  name: 'Paragon',
                  type: 'folder',
                  icon: 'FolderOpen',
                  color: 'purple',
                  description: 'Paragon project-specific BIM requirements, HPEP, and coordination guide.',
                  children: [
                    file('paragon-bim-req', 'paragon-bim-req',
                      'Hoffman BIM Requirements 2024-10-08.pdf', 'pdf', 520000,
                      'Contract BIM requirements for Paragon. Uses Newforma Konekt (not BIM Track), BBBDD-LLSYY naming, Jacobs/HPEP attribute references.',
                      [
                        'Issue tracking: Newforma Konekt (not BIM Track)',
                        'File naming: BBBDD-LLSYY-XX-MM-CCC format',
                        'LOD 400 for CM, do NOT over-model internals',
                        'Attributes: HCC_IFF_ID, HCC_OSM_ID, APM_POC, EQP_ID',
                      ],
                    ),
                    file('paragon-hpep', 'paragon-hpep',
                      'Hoffman Paragon HPEP for BIM 3D Design.pdf', 'pdf', 710000,
                      'Paragon CPEP for Applied Materials project. Covers roles, BIM 360, Newforma Konekt, DM/CM/FM, IFF (max 2 per day), model-to-field, and closeout.',
                      [
                        'Software: Revit 2023, Civil 3D/AutoCAD 2021, CADWorx 2020, Navisworks 2023',
                        'CM: no reuse of DM geometry -- detail accurate CM independently',
                        'IFF: max 2 submissions per day unless BIM Manager approves',
                        'IFF naming: LL-YY_IFF-BBB-AAA-XXXX_YYYY-MM-DD',
                        'Final payment withheld until record models approved',
                      ],
                    ),
                    file('paragon-coordination-guide', 'paragon-coordination-guide',
                      'Project PARAGON BIM Modeling and Coordination Guide.pdf', 'pdf', 331831,
                      'Owner/GC guide: design is across models + specs + drawings. Subs must combine into CMs, attend coordination 2x weekly, clash and track in BIM Track, IFF before install.',
                      [
                        'Use A-11 and A-7 to know what is modeled vs 2D',
                        'HCC CPEP Appendix 6.1 + Jacobs A-9 for deviation/RFI rules',
                        'Coordination meetings twice weekly minimum',
                      ],
                    ),
                  ],
                },
              ],
            },
            {
              id: 'f01',
              name: '01_CAD Standards',
              type: 'folder',
              icon: 'PenTool',
              color: 'slate',
              status: 'documents',
              description: 'Intel CAD Standards (ICS), file naming, shared parameters, and audit procedures.',
              quickStart: 'Every element needs INT_PKG_Name and INT_SSID parameters. Load the Shared Parameters file FIRST. File names follow: XCCBBB-LLL-UUU-DD-SSSSS-FFF-TT. Your model will be machine-audited via MPA.',
              children: [
                file('ics-cad-standards', 'ics-cad-standards',
                  'ICS 01_34_14_00 - CAD Standards.pdf', 'pdf', 1468225,
                  'The master Intel CAD Standard (ICS 13). Governs all file naming, shared parameters, coordinates, deliverables, titleblocks, and model setup rules.',
                  [
                    'File naming: XCCBBB-LLL-UUU-DD-SSSSS-FFF-TT format',
                    'Every element: INT_PKG_Name + INT_SSID parameters required',
                    'Shared coordinates mandatory for all linking and NWC export',
                    'No imported content, no in-place families without DMS approval',
                    'No 2D linework in sheet views -- annotation only',
                    'Models must be purged before delivery',
                    'Project units: 1/256" tolerance, no dimension overrides',
                  ],
                ),
                file('ics-file-audit', 'ics-file-audit',
                  'ICS File Audit Steps.pdf', 'pdf', 380271,
                  'Defines the 7-phase audit process that every model goes through. Know what gets checked so you pass on first submission.',
                  [
                    'Revit audit checks: filename, version, shared params, coordinates, imports, in-place families, groups, warnings',
                    'Failed IFC audit delays integration of future scope',
                    'Resubmissions must be complete packages, not just corrections',
                    'Phase 1-2: IFC audit, Phase 5-6: IFR audit',
                  ],
                ),
                file('shared-params-guide', 'shared-params-guide',
                  'Shared Parameters Revit Guide.pdf', 'pdf', 383898,
                  'Step-by-step guide to loading the Owner Shared Parameters into Revit. Do this BEFORE modeling anything.',
                  [
                    'Download .txt file from BIM360 GC folder > CAD Standards',
                    'Manage > Shared Parameters > Browse > select the .txt file',
                    'Add all params as Instance with "Values can vary by group instance"',
                    'Verify params appear in NWC export via Navisworks Properties panel',
                    'Always export NWC using Shared Coordinates',
                  ],
                ),
                file('ics-bb-flow', 'ics-bb-flow',
                  'Base Build Project Drawing Process Flow.pdf', 'pdf', 173980,
                  'Visual flowchart showing the basebuild project drawing lifecycle through the DMS pipeline.',
                ),
                file('ics-cad-standards-docx', 'ics-cad-standards-docx',
                  '01_34_14 Cad Standards.docx', 'docx', 203636,
                  'Word version of the CAD standards document for editing/reference.',
                ),
                {
                  id: 'eagle',
                  name: 'Eagle',
                  type: 'folder',
                  icon: 'FolderOpen',
                  color: 'slate',
                  description: 'Eagle-specific CAD standard files: layers, shared parameters, supplier codes, Revit families, and templates.',
                  children: [
                    file('eagle-ics-layers', 'eagle-ics-layers', 'ICS Layers.xlsx', 'xlsx', 184022,
                      'Layer naming standard spreadsheet. Defines all required layers by discipline.',
                    ),
                    file('eagle-shared-params-guide', 'eagle-shared-params-guide', 'Shared Parameters Revit Guide.docx', 'docx', 544346,
                      'Eagle-specific shared parameters guide for Revit setup.',
                    ),
                    file('eagle-shared-params-txt', 'eagle-shared-params-txt', 'Shared Parameters.txt', 'txt', 16178,
                      'The actual shared parameters text file to load into Revit.',
                    ),
                    file('eagle-shared-params-xlsx', 'eagle-shared-params-xlsx', 'Shared Parameters.xlsx', 'xlsx', 12607),
                    file('eagle-deliverables-index', 'eagle-deliverables-index', 'Deliverables Index.xlsx', 'xlsx', 40795,
                      'Template for the deliverables index that must accompany every submission.',
                    ),
                    file('eagle-rev-history', 'eagle-rev-history', 'Revision History.xlsx', 'xlsx', 22146),
                    file('eagle-revit-warnings', 'eagle-revit-warnings', 'Revit Warnings.xlsx', 'xlsx', 24245,
                      'Acceptable vs. unacceptable Revit warnings list. Fix all warnings not on this list before submission.',
                    ),
                    file('eagle-supplier-codes', 'eagle-supplier-codes', 'Supplier Codes.xlsx', 'xlsx', 36881),
                    file('eagle-titles-examples', 'eagle-titles-examples', 'Title Block Examples.docx', 'docx', 24921),
                    file('eagle-symbols', 'eagle-symbols', 'ICS Symbols.zipx', 'zipx', 5088858),
                    file('eagle-linetypes', 'eagle-linetypes', 'Intel Linetypes.zipx', 'zipx', 66265),
                    file('eagle-linetype-examples', 'eagle-linetype-examples', 'Linetype Examples.pdf', 'pdf', 23618),
                    file('eagle-hcc-osm-pod', 'eagle-hcc-osm-pod', 'HCC_OSM_POD.rfa', 'rfa', 503808),
                    file('eagle-int-poc', 'eagle-int-poc', 'INT_POC.rfa', 'rfa', 475136),
                    file('eagle-ics-changelog', 'eagle-ics-changelog', 'ICS Changelog.xlsx', 'xlsx', 329201),
                    file('eagle-supplier-request', 'eagle-supplier-request', 'Supplier Code Request Form.docx', 'docx', 20342),
                    file('eagle-cad-change-request', 'eagle-cad-change-request', 'CAD Standard Change Request Form.docx', 'docx', 35459),
                    file('eagle-ics-variance', 'eagle-ics-variance', 'ICS Variance Request - Design Model Workflow.docx', 'docx', 821463),
                    file('eagle-readme', 'eagle-readme', 'ReadMe.txt', 'txt', 1944),
                    file('eagle-acad-lin', 'eagle-acad-lin', 'acad.lin', 'lin', 16112),
                  ],
                },
                {
                  id: 'paragon',
                  name: 'Paragon',
                  type: 'folder',
                  icon: 'FolderOpen',
                  color: 'slate',
                  description: 'Paragon-specific CAD standards and shared parameter files.',
                  children: [
                    file('paragon-cad-stds', 'paragon-cad-stds', 'AppsLabsCADStdsRev3.doc', 'doc', 4253696),
                    file('paragon-shared-params', 'paragon-shared-params', 'Revit_Shared-Parameters.txt', 'txt', 1260),
                  ],
                },
              ],
            },
            {
              id: 'f02',
              name: '02_EOR PEP and Supporting Document',
              type: 'folder',
              icon: 'ScrollText',
              color: 'emerald',
              status: 'active',
              toolRoute: '/resources/tolerance',
              toolLabel: 'Tolerance Lookup',
              description: 'Engineer of Record documents: LOD matrix, change management tolerances, and deliverables format.',
              quickStart: 'Check A-9 tolerance table before moving any element. Subfab racks = 0" tolerance. Process piping in EOR racks = 1/2". Always log changes in BIM Track with viewpoint screenshots.',
              children: [
                file('a7-lod-matrix', 'a7-lod-matrix',
                  'A-7 LOD Matrix.xlsx', 'xlsx', 9784364,
                  'Level of Detail requirements by element type. Process piping = LOD 400 (fabrication-accurate). Check this before modeling to know what level of detail is required.',
                  [
                    'Process piping: LOD 400 (fabrication-accurate)',
                    'Elements below LOD threshold have more tolerance flexibility',
                    'Defines what metadata is required at each LOD level',
                  ],
                ),
                file('a9-change-mgmt-pptx', 'a9-change-mgmt-pptx',
                  'A-9 Change Management.pptx', 'pptx', 124629,
                  'Change management presentation with tolerance tables by discipline. THE critical reference for knowing how far you can deviate from the design model.',
                  [
                    'Subfab lateral racks: 0" tolerance (all disciplines)',
                    'Process piping in EOR racks: 1/2"',
                    'Utility mains & sub-mains: 1"',
                    'Individual pipe runs: 6"',
                    'Equipment/panel datums: 1/2"',
                    'Within tolerance + no conflict = no RFI needed',
                    'Outside tolerance = RFI required',
                    'ALL changes must be tracked in BIM Track with viewpoints',
                  ],
                ),
                file('a11-deliverables', 'a11-deliverables',
                  'A-11 Deliverables Format Table.pdf', 'pdf', 210665,
                  'Defines what to deliver and in what format. Lists required deliverables for each submission milestone.',
                  [
                    'Defines required file formats for each deliverable type',
                    'Lists submission milestones and what is due at each',
                  ],
                ),
                {
                  id: 'f02-eagle',
                  name: 'Eagle',
                  type: 'folder',
                  icon: 'FolderOpen',
                  color: 'emerald',
                  description: 'Eagle-specific EOR appendices: BIM PEP, use definitions, roles, workflows, LOD, software, clash detection, and deliverables.',
                  children: [
                    file('eagle-bim-pep', 'eagle-bim-pep', 'Project Eagle BIM PEP.docx', 'docx', 420000, 'Eagle Engineer of Record BIM Project Execution Plan. Defines Imperial/metric usage, discipline-specific procedures.'),
                    file('eagle-a2-cad-std', 'eagle-a2-cad-std', 'A-2.1 CAD Standards.docx', 'docx', 204000, 'Eagle CAD standard appendix from the EOR.'),
                    file('eagle-a2-site-handbook', 'eagle-a2-site-handbook', 'A-2.2 AZ-OC Site Handbook Rev5.pdf', 'pdf', 890000, 'Ocotillo campus site handbook with coordinates, buildings, and site rules.'),
                    file('eagle-a4-bim-uses', 'eagle-a4-bim-uses', 'A-4 BIM Use Definitions.docx', 'docx', 78000, 'Defines BIM use cases for Eagle: coordination, scheduling, cost, visualization.'),
                    file('eagle-a5-rr', 'eagle-a5-rr', 'A-5 Roles & Responsibilities.docx', 'docx', 85000, 'Detailed role descriptions for every BIM team position on Eagle.'),
                    file('eagle-a6-workflow', 'eagle-a6-workflow', 'A-6 Design Workflow.pptx', 'pptx', 175000, 'Design workflow presentation showing the Eagle project delivery sequence.'),
                    file('eagle-a7-lod', 'eagle-a7-lod', 'A-7 LOD Matrix (Eagle).xlsx', 'xlsx', 9784364, 'Eagle-specific LOD matrix by discipline and element type.'),
                    file('eagle-a8-software', 'eagle-a8-software', 'A-8 Authoring Software.docx', 'docx', 52000, 'Approved software and versions for Eagle: Revit 2021, AutoCAD 2018, Navisworks 2021.',
                      ['Revit 2021.1.x required', 'AutoCAD save as 2018 format', 'Navisworks Manage 2021', 'BIM Track for issue tracking'],
                    ),
                    file('eagle-a9-change', 'eagle-a9-change', 'A-9 Change Management (Eagle).pptx', 'pptx', 124629, 'Eagle change management tolerances by element category.'),
                    file('eagle-a10-clash', 'eagle-a10-clash', 'A-10 Clash Detection.pptx', 'pptx', 185000, 'Eagle clash detection procedures and adjudication process.'),
                    file('eagle-a11-deliverables', 'eagle-a11-deliverables', 'A-11 Deliverables Format Table (Eagle).pdf', 'pdf', 210665, 'Eagle-specific deliverable formats for each submission milestone.'),
                    file('eagle-cable-tray', 'eagle-cable-tray', 'Cable Tray Guidelines.pdf', 'pdf', 320000, 'Cable tray routing and fabrication guidance for Eagle.'),
                    file('eagle-clash-adjudications', 'eagle-clash-adjudications', 'Clash Adjudications.pptx', 'pptx', 195000, 'Clash resolution and adjudication process for Eagle coordination.'),
                    file('eagle-mepcon-colors', 'eagle-mepcon-colors', 'MEPCon Color Schemes.pdf', 'pdf', 240000, 'Color scheme standards for MEP coordination views.'),
                  ],
                },
                {
                  id: 'f02-paragon',
                  name: 'Paragon',
                  type: 'folder',
                  icon: 'FolderOpen',
                  color: 'purple',
                  description: 'Paragon-specific EOR appendices: BIM PEP, definitions, roles, workflows, LOD, software, and deliverables.',
                  children: [
                    file('paragon-bim-pep', 'paragon-bim-pep', 'Project Paragon Design BIM PEP.docx', 'docx', 420000, 'Paragon Engineer of Record BIM Project Execution Plan.'),
                    file('paragon-a1-definitions', 'paragon-a1-definitions', 'A-1 BIM Definitions.docx', 'docx', 68000, 'Paragon BIM terminology and definitions.'),
                    file('paragon-a2-file-naming', 'paragon-a2-file-naming', 'A-2 File Naming.xlsx', 'xlsx', 95000, 'Paragon file naming convention reference spreadsheet.'),
                    file('paragon-a3-layers', 'paragon-a3-layers', 'A-3 CAD Standards Layer List.xlsx', 'xlsx', 120000, 'Paragon layer naming standard spreadsheet.'),
                    file('paragon-a4-bim-uses', 'paragon-a4-bim-uses', 'A-4 BIM Use Definitions.docx', 'docx', 78000, 'Defines BIM use cases for Paragon.'),
                    file('paragon-a5-rr', 'paragon-a5-rr', 'A-5 Roles & Responsibilities.docx', 'docx', 85000, 'Role descriptions for every BIM team position on Paragon.'),
                    file('paragon-a6-workflow', 'paragon-a6-workflow', 'A-6 Design Workflow.pptx', 'pptx', 175000, 'Design workflow presentation for Paragon project delivery.'),
                    file('paragon-a7-lod', 'paragon-a7-lod', 'A-7 LOD Matrix (Paragon).xlsx', 'xlsx', 9784364, 'Paragon-specific LOD matrix by discipline and element type.'),
                    file('paragon-a8-software', 'paragon-a8-software', 'A-8 Authoring Software.docx', 'docx', 52000, 'Approved software and versions for Paragon.',
                      ['Revit 2023 required', 'Civil 3D/AutoCAD 2021, save as 2018', 'CADWorx 2020 for piping', 'Navisworks 2023'],
                    ),
                    file('paragon-a9-change', 'paragon-a9-change', 'A-9 Change Management (Paragon).pptx', 'pptx', 124629, 'Paragon change management tolerances by element category.'),
                    file('paragon-a10-clash', 'paragon-a10-clash', 'A-10 Clash Detection.pptx', 'pptx', 185000, 'Paragon clash detection procedures.'),
                    file('paragon-a11-deliverables-pdf', 'paragon-a11-deliverables-pdf', 'A-11 Deliverables Format Table.pdf', 'pdf', 210665, 'Paragon deliverable formats for each submission milestone.'),
                    file('paragon-a11-deliverables-docx', 'paragon-a11-deliverables-docx', 'A-11 Deliverables Format Table.docx', 'docx', 215000, 'Editable Word version of the Paragon deliverables table.'),
                  ],
                },
              ],
            },
            {
              id: 'f03', name: '03_Certified Model Content (CMC) Guides', type: 'folder',
              icon: 'Box', color: 'purple', status: 'documents',
              description: 'How to navigate Navisworks NWDs to find certified (contract) scope using selection sets. Understand what is CMC vs Issued vs Reconstructed.',
              quickStart: 'CMC = Certified Model Content = your contract scope. Navigate NWDs using: Unhide All > Select certified set > Hide Unselected. Never treat Issued/Reconstructed as contract documents.',
              children: [
                {
                  id: 'f03-eagle', name: 'Eagle', type: 'folder', icon: 'FolderOpen', color: 'purple',
                  description: 'Eagle CMC guide: BIM 360 folder layout, 6 rules, NWD naming, selection sets, QAQC clash orbs, future scope (FUTR layers).',
                  children: [
                    file('eagle-cmc-guide', 'eagle-cmc-guide',
                      'Eagle Certified Model Content Guide.pdf', 'pdf', 620000,
                      'Eagle CMC user guide. Explains certified vs uncertified scope in NWDs, BIM 360 folder layout, selection set navigation, QAQC clash orbs, and future scope layers.',
                      [
                        'CMC = stamped, selection-set-defined scope inside NWDs',
                        'Folder structure: Certified_BIM, Reconstructed, XM, QAQC, Source_Files',
                        'CMC + stamped PDFs = contract; source files = reference only',
                        'Future scope: CADWorx uses FUTR layers, Revit uses INT_FUTR parameter',
                        'Viewpoint naming per Intel CAD: VLCBB-... format',
                        'Adjudication types: adjust in field, acceptable encroachment',
                      ],
                    ),
                    file('eagle-cmc-guide-docx', 'eagle-cmc-guide-docx',
                      'Eagle Certified Model Content Guide.docx', 'docx', 580000,
                      'Editable Word version of the Eagle CMC guide.',
                    ),
                  ],
                },
                {
                  id: 'f03-paragon', name: 'Paragon', type: 'folder', icon: 'FolderOpen', color: 'purple',
                  description: 'Paragon CMC guide: Jacobs folder conventions, Paragon NWD naming, future scope (-F suffix), and selection set workflow.',
                  children: [
                    file('paragon-cmc-guide', 'paragon-cmc-guide',
                      'PARAGON CMC Certified Model Content Guide.pdf', 'pdf', 540000,
                      'Paragon CMC guide. Same workflow as Eagle (Unhide All > Select Set > Hide Unselected) but with Paragon naming and Jacobs folder conventions.',
                      [
                        'Folder: Drawings/DWGs, Models/Navis/Certified, Models/Navis/Issued, XM, QAQC, Models/RVT',
                        'NWD naming: YYMMDD_PKG_BLDG-LLLSS-GEN-DM-JEG_DD_ISS.nwd',
                        'Future scope: CADWorx uses -F suffix layers, Revit uses Future Build (yes/no)',
                        'Issued reconciled models are reference only for FM build',
                        'Extra adjudication type: Acceptable penetration(s)',
                      ],
                    ),
                  ],
                },
              ],
            },
            {
              id: 'f04', name: '04_File Naming Guides and UPN Lists', type: 'folder',
              icon: 'FileType', color: 'amber', status: 'documents',
              description: 'File naming conventions, unique project numbers (UPN), building maps, elevation maps, key plans, and supplier/author codes.',
              quickStart: 'Every file must follow the naming convention exactly -- it is machine-audited. Use the UPN list to find your building/level/sector codes. Check building maps for zone boundaries.',
              children: [
                {
                  id: 'f04-eagle', name: 'Eagle', type: 'folder', icon: 'FolderOpen', color: 'amber',
                  description: 'Eagle file naming guide, UPN lists, building maps for all buildings (FAB 52.1/52.2, BC2, T50-T52, etc.), key plans, and supplier codes.',
                  children: [
                    file('eagle-file-naming', 'eagle-file-naming',
                      'EAGLE File Naming Guide.xlsx', 'xlsx', 350000,
                      'Master file naming spreadsheet for Eagle. Lists every naming convention with examples for each discipline and file type.',
                      [
                        'Format: XCCBBB-LLL-UUU-DD-SSSSS-AAA-MM.ext',
                        'X=Campus, CC=Building, BBB=Code, LLL=Level, UUU=Zone, DD=Discipline',
                        'No revision numbers or dates in filenames',
                      ],
                    ),
                    file('eagle-upn-list-pdf', 'eagle-upn-list-pdf',
                      'EAGLE UPN List.pdf', 'pdf', 280000,
                      'PDF version of the Eagle Unique Project Number list. Maps every model file to building, level, sector, and discipline.',
                    ),
                    file('eagle-upn-list', 'eagle-upn-list',
                      'EAGLE UPN List.xlsx', 'xlsx', 320000,
                      'Searchable spreadsheet of all Eagle UPN assignments. Use this to find the correct UPN for your scope.',
                    ),
                    file('eagle-upn-layer-ref-pdf', 'eagle-upn-layer-ref-pdf',
                      'EAGLE UPN-Layer Reference Document.pdf', 'pdf', 260000,
                      'Cross-reference between UPN codes and layer naming conventions.',
                    ),
                    file('eagle-upn-layer-ref', 'eagle-upn-layer-ref',
                      'EAGLE UPN-Layer Reference Document.xlsx', 'xlsx', 290000,
                      'Searchable UPN-to-layer mapping spreadsheet.',
                    ),
                    file('eagle-building-elevations', 'eagle-building-elevations',
                      'Eagle Building Levels and Elevations.pdf', 'pdf', 310000,
                      'Building elevation reference showing level names, elevation values, and level code mapping for all Eagle buildings.',
                      [
                        'Maps level codes to descriptive names (e.g. 0BA=Basement, 3FA=Fab Floor)',
                        'Shows elevation values in feet for each level',
                        'Essential for file naming and model placement',
                      ],
                    ),
                    file('eagle-supplier-codes-04', 'eagle-supplier-codes-04',
                      'Author 3-Digit Code List.xlsx', 'xlsx', 36881,
                      'All 3-letter author/supplier codes for Eagle. Required for file naming and BIM Track issue titles.',
                    ),
                  ],
                },
                {
                  id: 'f04-paragon', name: 'Paragon', type: 'folder', icon: 'FolderOpen', color: 'amber',
                  description: 'Paragon file naming guide, 2D drawing codes, CM/FM maps, area maps, and key plans.',
                  children: [
                    file('paragon-file-naming', 'paragon-file-naming',
                      'PARAGON File Naming Guide.xlsx', 'xlsx', 350000,
                      'Master file naming spreadsheet for Paragon. Format: BBBDD-LLSYY-XX-MM-CCC.ext',
                      [
                        'Format: BBBDD-LLSYY-XX-MM-CCC.eee',
                        'BBB=Building, DD=Discipline, LL=Level, S=Sector, YY=System',
                      ],
                    ),
                    file('paragon-2d-codes', 'paragon-2d-codes',
                      'PARAGON 2D Drawing Codes.xlsx', 'xlsx', 95000,
                      'Drawing code reference for Paragon 2D deliverables.',
                    ),
                    file('paragon-cm-map', 'paragon-cm-map',
                      'Project PARAGON CM Map (2025-03-06).pdf', 'pdf', 420000,
                      'Latest Construction Model sector map for Paragon. Shows how the building is divided into CM sectors.',
                    ),
                    file('paragon-fm-map', 'paragon-fm-map',
                      'Project PARAGON FM Map (2025-03-06).pdf', 'pdf', 380000,
                      'Latest Federated Model sector map for Paragon. Shows FM structure and sector organization.',
                    ),
                  ],
                },
              ],
            },
            {
              id: 'f05', name: '05_RVT DWG Grids and Site Coordinates', type: 'folder',
              icon: 'Grid3x3', color: 'slate', status: 'documents',
              description: 'Revit shared coordinates setup guide, grid DWG/NWC reference files by building, and the project coordinate acquisition procedure.',
              quickStart: 'Set shared coordinates BEFORE modeling. Use the Acquiring Coordinates Guide and download the correct grid DWG for your building. Export test NWC to verify alignment in Navisworks.',
              children: [
                file('eagle-coordinates-guide', 'eagle-coordinates-guide',
                  'BIM Acquiring Project Coordinates Guide.docx', 'docx', 245000,
                  'Step-by-step guide to acquiring shared coordinates in Revit/Civil 3D for this project. Covers origin, survey point, project base point, and verification.',
                  [
                    'Set building models to Ocotillo Campus local coordinate system',
                    'Acquire coordinates from the project grid DWG before modeling',
                    'Export a test NWC and verify alignment in Navisworks',
                    'Civil models may arrive in civil CS -- trade models must align to campus/building',
                  ],
                ),
              ],
            },
            {
              id: 'f06', name: '06_Navisworks Configuration Files', type: 'folder',
              icon: 'ScanSearch', color: 'slate', status: 'documents',
              description: 'Navisworks setup files: Global Options, Quick Properties, Roamer Commands (keyboard shortcuts), Revit NWC Export Settings, and Search Sets. Download and install per your Navis version.',
              quickStart: 'Download the config files for your Navisworks version and project. Key settings: NWC export = Shared Coordinates, Linked Files = Off, Element IDs = On, Divide by Levels = Off.',
              children: [
                {
                  id: 'f06-eagle', name: 'Eagle', type: 'folder', icon: 'FolderOpen', color: 'slate',
                  description: 'Eagle Navisworks configuration: Global Options, Quick Properties per discipline, keyboard shortcuts, NWC export settings, and search sets.',
                  children: [
                    file('eagle-quick-props-dict', 'eagle-quick-props-dict',
                      'Quick Properties Dictionary.xlsx', 'xlsx', 148000,
                      'Defines which properties appear in the Navisworks Quick Properties panel for each discipline. Ensure your model metadata matches these fields.',
                      [
                        'Lists properties shown per discipline (Electrical, Plumbing, FP, etc.)',
                        'Your metadata must include these fields to be visible during coordination',
                      ],
                    ),
                    file('eagle-navis-shortcuts-pdf', 'eagle-navis-shortcuts-pdf',
                      'Navisworks Shortcut Quick Key Command List.pdf', 'pdf', 82000,
                      'Printable keyboard shortcut reference for Navisworks. Keep this at your desk.',
                      [
                        'Ctrl+H = Hide selection, Ctrl+1 = Select mode',
                        'F5 = Refresh, Ctrl+F = Quick find, F3 = Find next',
                        'Ctrl+A = Append model, Ctrl+M = Merge',
                      ],
                    ),
                    file('eagle-roamer-2025', 'eagle-roamer-2025',
                      'Roamer Command Standard 2025.pdf', 'pdf', 78000,
                      'Human-readable reference for the 2025 Navisworks Roamer keyboard command configuration.',
                    ),
                    file('eagle-roamer-2024', 'eagle-roamer-2024',
                      'Roamer Command Standard 2024.pdf', 'pdf', 78000,
                      'Human-readable reference for the 2024 Navisworks Roamer keyboard command configuration.',
                    ),
                  ],
                },
                {
                  id: 'f06-paragon', name: 'Paragon', type: 'folder', icon: 'FolderOpen', color: 'slate',
                  description: 'Paragon Navisworks configuration files. Same structure as Eagle but with Paragon-specific settings.',
                  children: [
                    file('paragon-quick-props-dict', 'paragon-quick-props-dict',
                      'Quick Properties Dictionary.xlsx', 'xlsx', 148000,
                      'Paragon version: which properties appear in Quick Properties panel per discipline.',
                    ),
                    file('paragon-global-options-doc', 'paragon-global-options-doc',
                      'HCC Navis Global Options 2024 Guide.docx', 'docx', 120000,
                      'Narrative guide explaining the Paragon Global Options settings for Navisworks 2024.',
                    ),
                  ],
                },
              ],
            },
            {
              id: 'f07', name: '07_BIM 360 Guide', type: 'folder',
              icon: 'Cloud', color: 'blue', status: 'documents',
              description: 'BIM 360 (Common Data Environment) setup guide. Folder structure, account requests, upload locations, permissions, and ADC (Autodesk Desktop Connector).',
              quickStart: 'BIM 360 is the single source of truth. Upload CM NWC + source files to folder 03_Subcontractor CM Uploads. Subscribe to 00_Welcome Package for updates. NWC export = Shared Coordinates, Divide by Levels unchecked.',
              children: [
                file('eagle-bim360-guide', 'eagle-bim360-guide',
                  'Eagle BIM 360 Docs Guide.pdf', 'pdf', 420000,
                  'Complete guide to Eagle BIM 360 CDE. Folder structure (00-10 + 98), account requests, upload rules, and permissions.',
                  [
                    'Account requests: email hoffman_automation@hoffmancorp.com',
                    '00_Welcome Package: subscribe for update notifications',
                    '01_Published FMs: non-dated NWDs auto-refresh when appended via ADC',
                    '03_Sub CM Uploads: upload NWC + DWG per building, shared coordinates',
                    '04_RVT Cloudshare: per-sub folders for live Revit models',
                    '06_IFC-DRB-RFI: design package model files from Jacobs',
                    '07_IFF Sign Off: approved IFF files archived here',
                    '10_Object Enablers: upload any required enablers for your software',
                  ],
                ),
                file('paragon-bim360-guide', 'paragon-bim360-guide',
                  'PARAGON BIM360 Docs and ADC Guide.pdf', 'pdf', 450000,
                  'Paragon CDE guide. Same folder structure as Eagle but Paragon-specific paths. Account requests go through Newforma Konekt contact.',
                  [
                    'Account requests: email wenxin-hu@hoffmancorp.com',
                    'Same 00-10 folder structure as Eagle',
                    'Live FM NWDs refresh automatically via ADC',
                    '02_NWF Files: contains NWFs/NWDs/NWCs that FM is built from',
                    'CM = Construction Model, DMI = Design Model Issued, DMW = Design Model WIP',
                  ],
                ),
              ],
            },
            {
              id: 'f08', name: '08_BIM Track / Newforma Konekt Guide', type: 'folder',
              icon: 'MessageSquareWarning', color: 'indigo', status: 'documents',
              description: 'Issue tracking guides: Eagle uses BIM Track, Paragon uses Newforma Konekt. Covers account setup, Navisworks integration, data fields, issue creation, DM review, coordination, IFF reporting, and design queries.',
              quickStart: 'Issue title format: SUB/SUB UPN(s) short description, MODIFIER. Types: 00_CM COORDINATION (most common), 01_DESIGN INQUIRY, 05_FIELD QUALITY OBSERVATION. Use Views to Issues for batch uploads.',
              children: [
                {
                  id: 'f08-eagle', name: 'Eagle (BIM Track)', type: 'folder', icon: 'FolderOpen', color: 'indigo',
                  description: 'BIM Track guides for Eagle: 8 sections covering setup through post-IFC issues.',
                  children: [
                    file('eagle-bt-sec1', 'eagle-bt-sec1',
                      'Sec 1 - Invitations, Accounts & Add-ins.pdf', 'pdf', 310000,
                      'BIM Track account setup: invitation flow, profile setup (add [HCC] before first name), and Navisworks/Revit add-in installation.',
                      [
                        'Request accounts via Contact List Request Form on BIM 360',
                        'Profile: add 3-letter author code in brackets before first name (e.g. [HCC] Alex)',
                        'Mark company point of contact with * (e.g. [HCC] *Alex)',
                        'Download add-in from BIM Track Integrations page',
                      ],
                    ),
                    file('eagle-bt-sec2', 'eagle-bt-sec2',
                      'Sec 2 - Navis Add-in, Data Parameters & Creating Issues.pdf', 'pdf', 580000,
                      'Core BIM Track reference: Navisworks integration, all data fields (Type, Status, Priority, Zone, Team Responsible), issue creation methods, and batch upload via Views to Issues.',
                      [
                        'Title format: SUB/SUB UPN(s) description, MODIFIER',
                        'Modifiers: APPROVED(?), TYP, RFI(?)',
                        'Types: 00_CM COORDINATION, 01_DESIGN INQUIRY, 03_TRIAD ESCALATION, 05_FIELD QUALITY',
                        'Status: 00_OPEN, 01_CLOSED, 02_RECONCILED, 04_FIELD COORDINATE',
                        'Views to Issues = recommended batch upload method',
                        'Set Navisworks image output to low-res before creating issues',
                      ],
                    ),
                    file('eagle-bt-sec3', 'eagle-bt-sec3',
                      'Sec 3 - BIM Track Web Interface.pdf', 'pdf', 420000,
                      'Using the BIM Track web application: filtering, quick filters, dashboards, and issue management.',
                    ),
                    file('eagle-bt-sec4-hcc', 'eagle-bt-sec4-hcc',
                      'Sec 4 - DM Package Review (HCC).pdf', 'pdf', 390000,
                      'How HCC reviews design model packages in BIM Track.',
                    ),
                    file('eagle-bt-sec4-jeg', 'eagle-bt-sec4-jeg',
                      'Sec 4 - DM Package Review (JEG).pdf', 'pdf', 390000,
                      'How Jacobs reviews design model packages in BIM Track.',
                    ),
                    file('eagle-bt-sec5', 'eagle-bt-sec5',
                      'Sec 5 - Construction Coordination Issue Management.pdf', 'pdf', 340000,
                      'Managing coordination issues during construction: creating, directing, responding, and closing issues between trades.',
                    ),
                    file('eagle-bt-sec6', 'eagle-bt-sec6',
                      'Sec 6 - Issue Reporting for IFF Submittal.pdf', 'pdf', 280000,
                      'How to document and report BIM Track issues as part of the IFF submittal process.',
                    ),
                    file('eagle-bt-sec7-sub', 'eagle-bt-sec7-sub',
                      'Sec 7.1 - Pre-IFC Design Queries (SUB team).pdf', 'pdf', 290000,
                      'How subcontractors raise pre-IFC design queries. Title: AAA/DMxx, type: 01_DESIGN QUERY.',
                    ),
                    file('eagle-bt-sec7-cm', 'eagle-bt-sec7-cm',
                      'Sec 7.2 - Pre-IFC Design Queries (CM team).pdf', 'pdf', 290000,
                      'How CM team handles pre-IFC design queries.',
                    ),
                    file('eagle-bt-sec7-dm', 'eagle-bt-sec7-dm',
                      'Sec 7.3 - Pre-IFC Design Queries (DM team).pdf', 'pdf', 290000,
                      'How the design team responds to pre-IFC design queries.',
                    ),
                    file('eagle-bt-sec8-sub', 'eagle-bt-sec8-sub',
                      'Sec 8.1 - Post-IFC Design Issues (SUB team).pdf', 'pdf', 310000,
                      'Subcontractor guide for raising design issues after IFC release.',
                    ),
                    file('eagle-bt-sec8-cm', 'eagle-bt-sec8-cm',
                      'Sec 8.2 - Post-IFC Design Issues (CM team).pdf', 'pdf', 310000,
                      'CM team guide for handling post-IFC design issues.',
                    ),
                    file('eagle-bt-quickbase', 'eagle-bt-quickbase',
                      'BIM Track Quickbase Design Package Training.pdf', 'pdf', 420000,
                      'Training document for using Quickbase integration with BIM Track design packages.',
                    ),
                  ],
                },
                {
                  id: 'f08-paragon', name: 'Paragon (Newforma Konekt)', type: 'folder', icon: 'FolderOpen', color: 'purple',
                  description: 'Newforma Konekt guides for Paragon: invitations, web interface, design issues, and issue naming.',
                  children: [
                    file('paragon-nfk-sec1', 'paragon-nfk-sec1',
                      'Sec 1 - Invitations, Accounts & Add-ins.pdf', 'pdf', 380000,
                      'Newforma Konekt account setup and add-in installation for Paragon.',
                    ),
                    file('paragon-nfk-sec3', 'paragon-nfk-sec3',
                      'Sec 3 - Web Interface.pdf', 'pdf', 450000,
                      'Using the Newforma Konekt web interface for issue management.',
                    ),
                    file('paragon-nfk-sec5', 'paragon-nfk-sec5',
                      'Sec 5 - Design Issues.pdf', 'pdf', 320000,
                      'Creating and managing design issues in Newforma Konekt for Paragon.',
                    ),
                    file('paragon-nfk-naming', 'paragon-nfk-naming',
                      'Newforma Konekt Issue Naming Guide.pdf', 'pdf', 95000,
                      'Issue naming standard for Paragon. Same SUB/SUB format as Eagle BIM Track but with Paragon-specific modifiers.',
                      [
                        'Format: SUB/SUB short description, MODIFIER',
                        'First SUB listed is responsible for fixing the issue',
                        'For JEG issues: use DM + discipline code (e.g. DME0 = DM electrical)',
                        'Modifiers: APPROVED, ACCEPTABLE, RFI NEEDED/SENT/FOLLOWED, WITHIN A9, UPDATE MODEL',
                        'WITHIN A9 = DM deviation within tolerance, no JEG approval needed',
                      ],
                    ),
                  ],
                },
              ],
            },
            {
              id: 'f09', name: '09_Search Sets Guide', type: 'folder',
              icon: 'Search', color: 'slate', status: 'documents',
              description: 'Navisworks search set vs selection set guide. How to safely navigate published NWDs and use Jacobs CMC and Hoffman federated model sets.',
              quickStart: 'Search sets = dynamic (survive model updates). Selection sets = static (can break). NEVER click folder names in Navisworks -- use triangle dropdowns only. Hiding clearance zones risks missing clashes.',
              children: [
                file('eagle-search-sets', 'eagle-search-sets',
                  'HCC Eagle Search and Selection Sets Guide.pdf', 'pdf', 380000,
                  'Hoffman guide to Navisworks search vs selection sets. Covers safe navigation, Jacobs CMC set structure, and Hoffman federated model sets.',
                  [
                    'Search sets = dynamic filters, re-run on model updates',
                    'Selection sets = static groups, break when geometry changes',
                    'DO NOT click folder names -- triggers slow full-folder searches, use triangle dropdown',
                    'Jacobs CMC: use only the CMC selection set for contract scope isolation',
                    'Do not manually edit Issued selection sets -- report errors to Hoffman',
                    'Hiding clearance zones risks missing clashes',
                  ],
                ),
              ],
            },
            {
              id: 'f10', name: '10_BIM Workflow Documents', type: 'folder',
              icon: 'Workflow', color: 'indigo', status: 'documents',
              description: 'Visual flowcharts for every BIM workflow: design delivery, federated model structure, BIM collaboration (minor vs major deviation), design queries, IFF submittal, and model-to-field quality review.',
              quickStart: 'Start with the Design Delivery Workflow to understand the DM > CM > FM chain. Use the Collaboration Workflow when you find a clash. Use the IFF Procedure when ready to submit.',
              children: [
                {
                  id: 'f10-eagle', name: 'Eagle', type: 'folder', icon: 'FolderOpen', color: 'indigo',
                  description: 'Eagle workflow diagrams: 8 appendix flowcharts covering the full BIM lifecycle.',
                  children: [
                    file('eagle-wf-design-delivery', 'eagle-wf-design-delivery',
                      'Appendix 4.1 - Design Delivery Workflow.pdf', 'pdf', 185000,
                      'Swimlane diagram showing the DM > CM > FM chain: design models (WIP vs issued), construction models, federated model publish, and distribution via BIM 360/Procore.',
                    ),
                    file('eagle-wf-fm-structure', 'eagle-wf-fm-structure',
                      'Appendix 4.2 - Federated Model Structure.pdf', 'pdf', 165000,
                      'Diagram of FM composition: CM uploads, transmitted DMs, approved IFF, and named NWD deliverables (DM_ISSUED, DM_WIP, CM).',
                    ),
                    file('eagle-wf-best-value', 'eagle-wf-best-value',
                      'Appendix 6.2 - Best Value Heat Sheet Workflow.pdf', 'pdf', 145000,
                      'Best value heat sheet process for prioritizing coordination work.',
                    ),
                    file('eagle-wf-collaboration', 'eagle-wf-collaboration',
                      'Appendix 6.3 - BIM Collaboration Workflow.pdf', 'pdf', 175000,
                      'Decision flow for minor vs major deviation from design model, BIM Track issues, clash scope, RFI path, and when to start IFF.',
                      [
                        'Major deviation: multi-discipline impact, design input via DRB/RFI',
                        'Minor deviation: limited scope, within tolerance',
                        'Clashes feed BIM Track -- coordinate before treating work as done',
                      ],
                    ),
                    file('eagle-wf-design-query', 'eagle-wf-design-query',
                      'Appendix 6.4 - BIM Track Pre-IFC Design Query Workflow.pdf', 'pdf', 190000,
                      'BIM Track lifecycle for design queries pre-IFC: ticket fields, naming (AAA/DMxx), review loops, RFI escalation, TRIAD paths.',
                    ),
                    file('eagle-wf-iff', 'eagle-wf-iff',
                      'Appendix 7.1 - IFF Submittal Procedure.pdf', 'pdf', 155000,
                      'IFF gate process: conceptual review > HCC CM approval > HCC BIM technical review > schedule impact/SCN > re-IFF after major changes.',
                    ),
                    file('eagle-wf-field-quality', 'eagle-wf-field-quality',
                      'Appendix 8.1 - Model to Field Quality Review.pdf', 'pdf', 185000,
                      'Model-to-field quality loop: identify issues, BIM Track/Procore documentation, model vs field fix, gating vs non-gating for green tag.',
                      [
                        'D1 to F1: ~2 weeks timeline',
                        'F4 to H2: ~1-4 weeks depending on branch',
                        'Gating implications for green tag',
                      ],
                    ),
                    file('eagle-wf-tool-install', 'eagle-wf-tool-install',
                      'Intel SPARROW-EAGLE Tool Install & Base Build Coordination.pdf', 'pdf', 520000,
                      'Tool install and base build coordination procedures for Intel projects.',
                    ),
                  ],
                },
                {
                  id: 'f10-paragon', name: 'Paragon', type: 'folder', icon: 'FolderOpen', color: 'purple',
                  description: 'Paragon workflow diagrams: same structure as Eagle but using Newforma Konekt and Paragon-specific procedures.',
                  children: [
                    file('paragon-wf-design-delivery', 'paragon-wf-design-delivery',
                      'PARAGON Design Delivery Workflow.pdf', 'pdf', 175000,
                      'Paragon design delivery: BIM 360 for models, Procore for drawings/specs/RFIs. Follows package isolation and FM update steps.',
                    ),
                    file('paragon-wf-fm-structure', 'paragon-wf-fm-structure',
                      'PARAGON Federated Model Structure.pdf', 'pdf', 165000,
                      'Paragon FM includes DM_ISSUED/DM_WIP NWDs, CM.NWD, and inter-project coordination models.',
                    ),
                    file('paragon-wf-collaboration', 'paragon-wf-collaboration',
                      'PARAGON BIM Collaboration Workflow.pdf', 'pdf', 175000,
                      'Same minor vs major deviation logic as Eagle but uses Newforma Konekt and references Jacobs A-9 tolerances.',
                    ),
                    file('paragon-wf-iff', 'paragon-wf-iff',
                      'PARAGON IFF Submittal Procedure Workflow.pdf', 'pdf', 155000,
                      'IFF flow with Procore, HCC CM/BIM review, weekly sub meetings covering IFFs, DRBs, RFIs, design compliance review.',
                    ),
                    file('paragon-wf-field-quality', 'paragon-wf-field-quality',
                      'PARAGON Model to Field Quality Review Workflow.pdf', 'pdf', 175000,
                      'Paragon model-to-field: NF Konekt documentation, Procore close loops, same gating logic as Eagle.',
                    ),
                  ],
                },
              ],
            },
            {
              id: 'f11', name: '11_Meeting Schedules', type: 'folder',
              icon: 'CalendarDays', color: 'slate', status: 'documents',
              description: 'Weekly BIM coordination meeting schedule with time blocks and team assignments.',
              quickStart: 'Upload files at least 1 day before your scheduled meeting. Bring your BIM team AND field team representatives. Come prepared with your clash report.',
              children: [
                file('eagle-meeting-schedule', 'eagle-meeting-schedule',
                  'EAGLE BIM Coordination Meeting Schedule.pdf', 'pdf', 145000,
                  'Weekly coordination meeting grid with time blocks, team assignments (Fab, corridors, integrator), and named roles.',
                  [
                    'Know which time slot/team covers your building area',
                    'Upload files 1 day before your scheduled meeting',
                    'Bring field team representatives for constructability input',
                  ],
                ),
              ],
            },
            {
              id: 'f12', name: '12_IFF Submittal Guide', type: 'folder',
              icon: 'ClipboardCheck', color: 'amber', status: 'documents',
              description: 'Issued for Fabrication (IFF) submittal process: Procore workflow, pre-submit checklists, description templates, review timelines, naming conventions, and revision procedures.',
              quickStart: 'IFF = reservation of space + mitigation of risk. Schedule in Smartsheet FIRST, then submit on Procore. Spec section 00_00_00_20. CM review ~3 days, BIM review ~5 days. Max 2 IFF per day.',
              children: [
                {
                  id: 'f12-eagle', name: 'Eagle', type: 'folder', icon: 'FolderOpen', color: 'amber',
                  description: 'Eagle IFF guides: Procore workflow, CM checklist, MOD 2 scheduling, and description template.',
                  children: [
                    file('eagle-iff-workflow', 'eagle-iff-workflow',
                      'Eagle IFF Workflow SUB Rev.14.pdf', 'pdf', 780000,
                      'Full Procore IFF training (20 slides): IFF as submittals under spec 00_00_00_20, pre-submit checklist, Procore fields, description template, clash settings, and revision procedures.',
                      [
                        'IFF via Procore under spec section 00_00_00_20',
                        'Sub owns IFF numbering',
                        'Pre-submit: LOD 400, tagging, clash, BIM Track, BIM 360 upload',
                        'CM review ~3 days, BIM review ~5 days',
                        'Clash settings: Hard / Surfaces / 1/32"',
                        'No 3D attachments in Procore',
                        'Description must include: job, UPN, RFIs, BIM Track items, NWC filenames',
                      ],
                    ),
                    file('eagle-iff-checklist', 'eagle-iff-checklist',
                      'IFF Submission Checklist for CMs Rev3.pdf', 'pdf', 320000,
                      'CM pre-approval checklist: constructability, IFF tagging, clash report, Procore completeness, BIM Track/RFIs closed.',
                      [
                        'Fly scope and colorize tagged vs untagged geometry',
                        'Prove search set isolation for IFF scope',
                        'Separate submittals when IFC phase or building differs',
                        'All BIM Track and design queries must be closed or owned',
                      ],
                    ),
                    file('eagle-mod2-schedule', 'eagle-mod2-schedule',
                      'Eagle MOD 2 Scheduling.pdf', 'pdf', 280000,
                      'IFF scheduling via Smartsheet. Date changes via comments with @CM. CM updates Expected Start and Expected IFF Approval.',
                    ),
                    file('eagle-procore-template', 'eagle-procore-template',
                      'ProCore IFF Description Template.txt', 'txt', 450,
                      'Copy-paste template for Procore IFF description: fill in job, bid package, building, level, area, UPNs, RFIs, BIM Track items, and NWC file names with dates.',
                    ),
                  ],
                },
                {
                  id: 'f12-paragon', name: 'Paragon', type: 'folder', icon: 'FolderOpen', color: 'purple',
                  description: 'Paragon IFF guides: sections for Subcontractors, CMs, and Shops (SRM packages), plus checklists.',
                  children: [
                    file('paragon-iff-sec1', 'paragon-iff-sec1',
                      'Sec 1 - IFF Guide (Subcontractor).pdf', 'pdf', 680000,
                      'IFF definition, Smartsheet scheduling (required columns), Procore steps, workflow (CM then BIM), response types, and revision rules.',
                      [
                        'Schedule in Smartsheet BEFORE Procore submission',
                        'Procore spec: 00 00 00 20, use BIM IFF template',
                        'Responses: Approved / Approved as noted / Revise & Resubmit',
                        'Only revise on R&R -- use Update & Send Emails',
                        'Attach IFF checklist to every submission',
                      ],
                    ),
                    file('paragon-iff-sec2', 'paragon-iff-sec2',
                      'Sec 2 - IFF Guide (CM).pdf', 'pdf', 720000,
                      'CM IFF review: Navisworks isolation steps (use triangle not folder), Find Items by IFF number, CM checklist (NFK, Procore, LOD 400, DM overlay, A-9 tolerances).',
                      [
                        'Navis: Hoffman > SUBCONTRACTOR IFF sets > triangle dropdown',
                        'Find Items by IFF number, update clash selection set',
                        'NF Konekt fields and A-9 deviation documentation mandatory',
                      ],
                    ),
                    file('paragon-iff-sec3', 'paragon-iff-sec3',
                      'Sec 3 - IFF Guide (Shops/SRM).pdf', 'pdf', 560000,
                      'Shop (SRM) package guide: build selection sets per IFF, save as SRM-PARAGON-TLA_YYYY-MM-DD.nwd, attach to Procore.',
                    ),
                    file('paragon-iff-checklist', 'paragon-iff-checklist',
                      'PARAGON IFF Submittal Checklist for Subs.pdf', 'pdf', 310000,
                      'Sub-facing IFF checklist: model, NFK, Procore, resubmittal updates. Attach to every IFF submission as audit trail.',
                    ),
                    file('paragon-iff-cm-checklist', 'paragon-iff-cm-checklist',
                      'Sec 2 - CM Review Checklist.pdf', 'pdf', 295000,
                      'Standalone CM review sign-off form for each IFF review criterion.',
                    ),
                  ],
                },
              ],
            },
            {
              id: 'f13', name: '13_Clash Reporting Process', type: 'folder',
              icon: 'AlertOctagon', color: 'red', status: 'documents',
              description: 'Three-part clash reporting guide: IFF setup (selection sets, color coding), clash report generation (batches, viewpoints, self-clash), and re-review process.',
              quickStart: 'Color coding: Grey = CM files, Yellow = DM slice, Red = IFF scope. Run clash batches top-down, then self-clash with "Items in same file" disabled. Upload viewpoints to BIM Track.',
              children: [
                file('eagle-clash-part1', 'eagle-clash-part1',
                  'Part 1 - IFF Clash Setup.pdf', 'pdf', 640000,
                  'Setup for IFF clash reporting: selection sets for CM (grey), DM (yellow), IFF (red), untagged geometry QA, and clash batch configuration.',
                  [
                    'CM files = grey, DM comparison = yellow, IFF scope = red',
                    'Update "Clash Report Selection Set" before running',
                    'Check for untagged geometry -- it must be included or clashes will be missed',
                    'Clash batches are mostly preloaded -- use Update All',
                  ],
                ),
                file('eagle-clash-part2', 'eagle-clash-part2',
                  'Part 2 - Clash Report.pdf', 'pdf', 580000,
                  'Running clash tests: top-down batches, grouping, viewpoints, self-clash setup, and uploading to BIM Track.',
                  [
                    'Run batches top-down, group clashes by type',
                    'Self-clash: disable "Items in the same file", folder "Approved Non-Issues - Self"',
                    'Viewpoint naming: SUB vs SUB - description',
                    'Upload viewpoints to BIM Track, supplement Procore IFF response',
                  ],
                ),
                file('eagle-clash-part3', 'eagle-clash-part3',
                  'Part 3 - Re-review of Same IFF.pdf', 'pdf', 390000,
                  'Re-review process: relink NWF to latest NWD, folder "Already in BIM Track", repeat QA, compare against prior reviews.',
                  [
                    'Relink NWF to latest NWD before rerun',
                    'New clashes outside prior folders are genuinely new',
                    'Dated subfolders for repeat reviews',
                    'Conditional findings still need tracking even if IFF proceeds',
                  ],
                ),
              ],
            },
            {
              id: 'f14', name: '14_NSFP (Fire Protection Head Code)', type: 'folder',
              icon: 'Flame', color: 'red', status: 'documents',
              description: 'NFPA 13 sprinkler head blockage awareness: clearance zones, obstruction rules, code references, and model-to-field accuracy for fire protection.',
              quickStart: 'Model 24" dia x 12" deep clearance zone around every sprinkler head. 18" below deflector. 12" from horizontal/vertical obstructions. CM "owns" installable routing.',
              children: [
                file('eagle-nfpa13', 'eagle-nfpa13',
                  'Eagle NFPA 13 Training Package.pdf', 'pdf', 1250000,
                  '29-slide NFPA 13 awareness training: sprinkler head blockage rules, code references, clearance zones, seismic bracing, and model-to-field accuracy.',
                  [
                    'NFPA 11.3.6.1: sprinkler head blockage rules',
                    'NFPA 9.5.5.2: 18" below deflector clearance',
                    'NFPA 10.2.7.2: 3x max dimension rule for obstructions',
                    '24" diameter x 12" deep clearance zone around heads (project rule)',
                    '12" clearance to horizontal/vertical obstructions',
                    'Common obstructions: MEP supports, duct, conduit, FP pipe',
                    'Model seismic bracing explicitly',
                    'Field install must match IFF within ±1" tolerance',
                  ],
                ),
              ],
            },
            {
              id: 'f15', name: '15_Close Out', type: 'folder',
              icon: 'FolderArchive', color: 'slate', status: 'documents',
              description: 'Project closeout requirements: Intel/MPA audit, file submission rules, prerequisites, AutoCAD/Revit checklists, and naming formats. Final payment is withheld until approved.',
              quickStart: 'Start meeting closeout requirements EARLY. Max 20 files per review, max 2 reviews/day. All BIM Track issues must be reconciled. Source + NWC submitted together. Revit = entire file must be complete.',
              children: [
                {
                  id: 'f15-eagle', name: 'Eagle', type: 'folder', icon: 'FolderOpen', color: 'slate',
                  description: 'Eagle closeout: Intel MPA audit, BIM 360 submit workflow, ticker naming, and sub guide.',
                  children: [
                    file('eagle-closeout-guide', 'eagle-closeout-guide',
                      'Closeout Guide for Subs.pdf', 'pdf', 480000,
                      'Intel audit closeout guide: max 20 files per review, prerequisites (Procore closed, IFF complete, BIM Track reconciled), AutoCAD/Revit checklists, B360 submit workflow.',
                      [
                        'Max 20 files per review without coordinator approval',
                        'Max 2 reviews per day per trade per building',
                        'Prerequisites: Procore observations closed, IFF complete, BIM Track reconciled',
                        'Revit: version 2021, grids correct, no xref links, package on 3D objects, purged',
                        'Submit DWG+NWC or RVT+all NWCs together',
                        'Cannot partial-closeout a single RVT file',
                        'Review naming: BLDG-COMPANY-Ticker###-LEVEL-M1/M2',
                      ],
                    ),
                    file('eagle-closeout-workflow', 'eagle-closeout-workflow',
                      'Closeout Workflow.pdf', 'pdf', 220000,
                      'One-page flowchart: prerequisites > B360 Intel 3D audit > Hoffman review > pass/fail > lock files. Intel reject = new ticker, Hoffman reject = reuse ticker.',
                    ),
                  ],
                },
                {
                  id: 'f15-paragon', name: 'Paragon', type: 'folder', icon: 'FolderOpen', color: 'purple',
                  description: 'Paragon closeout: BIM file audit, Revit 2023, naming conventions, and workflow.',
                  children: [
                    file('paragon-closeout', 'paragon-closeout',
                      'PARAGON BIM Closeout.pdf', 'pdf', 520000,
                      'Paragon closeout before final payment: submit NWCs/NWDs + source (dwg/rvt/ifc), naming standard, layer compliance, RFIs incorporated, NFK + Procore clear.',
                      [
                        'Revit 2023 (vs Eagle 2021)',
                        'Submit NWC/NWD + source files (DWG/RVT/IFC/Tekla)',
                        'RFIs must be incorporated into record models',
                        'NF Konekt + Procore must be clear',
                        '±1" accuracy for record models',
                        'Failed internal review: resubmit under same package number',
                        'Closeout naming: SUB-CRD03C.00-0001 style',
                      ],
                    ),
                  ],
                },
              ],
            },
            {
              id: 'f16', name: '16_BIM to Field QA', type: 'folder',
              icon: 'ClipboardList', color: 'emerald', status: 'active',
              toolRoute: '/upload', toolLabel: 'P&ID Extraction',
              description: 'Quality assurance for model-to-field accuracy and installation verification.',
              children: [],
            },
          ],
        },
        {
          id: 'models',
          name: '7.20.01 Project BIM Models',
          type: 'folder',
          icon: 'Layers',
          color: 'slate',
          status: 'coming_soon',
          description: 'Published federated models and design models.',
          children: [
            {
              id: 'models-published', name: '7.20.01.01 Published Federated Models', type: 'folder',
              icon: 'FolderOpen', color: 'slate', status: 'coming_soon',
              description: 'Published federated models for coordination.',
              children: [],
            },
            {
              id: 'models-design', name: '7.20.01.02 Design Models', type: 'folder',
              icon: 'FolderOpen', color: 'slate', status: 'coming_soon',
              description: 'Design models by discipline.',
              children: [],
            },
          ],
        },
      ],
    },
    {
      id: 'plansrow',
      name: 'Plansrow Reference',
      type: 'folder',
      icon: 'BookOpen',
      color: 'purple',
      description: 'Plansrow internal BIM manuals, cheat sheets, and reference materials.',
      children: [
        file('bim-manual-v2', 'bim-manual-v2',
          'Plansrow BIM Manual v2.pdf', 'pdf', 1039613,
          'The primary BIM standards manual for all Process BIM activities at Plansrow. Covers file management, LOD 400 rules, coordination workflow, change management, IFF process, and field updates.',
          [
            'Model everything to LOD 400 fabrication accuracy',
            'File naming: BBBDD-LLSYY-XX-MM-CCC.eee',
            'BIM 360 folder structure: 01 DM > 02 CM > 03 FM > 04 IFF > 05 As-Built',
            'Include insulation in true OD',
            'Tag every element with full metadata (Tag ID, System, Material, Size, Elevation, IFF Status)',
            'Run self-clash before coordination uploads',
            'Follow A-9 tolerances strictly -- document ALL deviations in BIM Track',
            'IFF locked after approval -- no changes without Re-IFF',
          ],
        ),
        file('bim-piping-cheat-sheet', 'bim-piping-cheat-sheet',
          'BIM Piping Cheat Sheet.pdf', 'pdf', 14214,
          'Quick-reference desk companion for BIM modelers. Covers abbreviations, LOD definitions, and pre-built answers for common stakeholder questions.',
          [
            'Abbreviation tables for BIM, piping, MEP, valves, instruments, file formats, survey',
            'LOD 100-500 one-liner definitions',
            'Q&A matrix for common meeting questions',
          ],
        ),
        file('a9-change-mgmt-pdf', 'a9-change-mgmt-pdf',
          'A-9 Change Management (PDF).pdf', 'pdf', 283216,
          'PDF version of the A-9 Change Management document with full tolerance tables by discipline.',
        ),
        file('bim-coordination-guide-root', 'bim-coordination-guide-root',
          'BIM Modeling and Coordination Guide.pdf', 'pdf', 331831,
          'Root copy of the Project Confluence BIM Modeling and Coordination Guide.',
        ),
      ],
    },
    {
      id: 'gf-lib',
      name: 'GF Pipes Library',
      type: 'folder',
      icon: 'Package',
      color: 'emerald',
      description: 'Georg Fischer technical documentation for plastic piping systems.',
      children: [
        file('gf-technical-handbook', 'gf-technical-handbook',
          'GF Contain-IT Double Containment Handbook.pdf', 'pdf', 3114797,
          'Technical handbook for Georg Fischer double containment piping systems. Reference for secondary containment pipe support rules.',
        ),
        file('gf-semiconductor-ref', 'gf-semiconductor-ref',
          'GF SYGEF Plus Semiconductor Reference Case.pdf', 'pdf', 1676346,
          'Reference case study for GF SYGEF Plus in semiconductor wafer cleaning applications.',
        ),
        file('gf-support-companies', 'gf-support-companies',
          'Pipe Support Companies.pdf', 'pdf', 4643,
          'List of approved pipe support hardware manufacturers.',
        ),
      ],
    },
    {
      id: 'asme',
      name: 'ASME B31.3-2024',
      type: 'folder',
      icon: 'FileText',
      color: 'slate',
      description: 'ASME Process Piping Code -- the governing code for process piping design.',
      children: [
        file('asme-b31-3', 'asme-b31-3',
          'ASME B31.3-2024.pdf', 'pdf', 12058370,
          'Full ASME B31.3 Process Piping Code. The governing code referenced by 40_05_19 for pipe support design.',
        ),
      ],
    },
  ],
};

export function flattenTree(node: ResourceNode): ResourceNode[] {
  const result: ResourceNode[] = [node];
  if (node.children) {
    for (const child of node.children) {
      result.push(...flattenTree(child));
    }
  }
  return result;
}

export function findNodeById(id: string, root: ResourceNode = RESOURCE_TREE): ResourceNode | undefined {
  if (root.id === id) return root;
  if (root.children) {
    for (const child of root.children) {
      const found = findNodeById(id, child);
      if (found) return found;
    }
  }
  return undefined;
}

export function getParentPath(targetId: string, root: ResourceNode = RESOURCE_TREE, path: ResourceNode[] = []): ResourceNode[] | null {
  if (root.id === targetId) return path;
  if (root.children) {
    for (const child of root.children) {
      const found = getParentPath(targetId, child, [...path, root]);
      if (found) return found;
    }
  }
  return null;
}

export function searchTree(query: string, root: ResourceNode = RESOURCE_TREE): ResourceNode[] {
  const q = query.toLowerCase();
  return flattenTree(root).filter(
    (n) =>
      n.name.toLowerCase().includes(q) ||
      n.description?.toLowerCase().includes(q) ||
      n.modelerSummary?.toLowerCase().includes(q) ||
      n.keyTakeaways?.some((t) => t.toLowerCase().includes(q))
  );
}

export function countFiles(node: ResourceNode): number {
  if (node.type === 'file') return 1;
  return (node.children || []).reduce((sum, c) => sum + countFiles(c), 0);
}
